name: ansible-lint

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint jmespath
      - name: Analysing playbook
        run: |
          ansible-lint *.yml -x 303,701,601,206,208 -v
